fix: add more -Wno- flags for OOS 4.19 + clang 19
hybridswap_eswap.c:544 error: type specifier missing [-Werror,-Wimplicit-int]
Add -Wno-implicit-int, -Wno-int-to-pointer-cast, -Wno-pointer-to-int-cast,
-Wno-implicit-function-declaration, -Wno-unused-but-set-variable to KCFLAGS.